defaults:
  - _self_
  - override hydra/launcher: submitit_slurm

hydra:
  run:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
  sweep:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 16
    mem_gb: 256
    gres: "gpu:h100:1"
    qos: "explore"
    timeout_min: 720
    setup: ["export DEBUGVAR=$(scontrol show hostnames $SLURM_JOB_NODELIST)",
            export MASTER_ADDR="$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)",
            "export MASTER_PORT=$(for port in $(shuf -i 30000-65500 -n 20); do if [[ $(netstat -tupln 2>&1 | grep $port | wc -l) -eq 0 ]] ; then echo $port; break; fi; done;)",]

# model to load for planning
ckpt_base_path: /root/DINO-WM-Metadrive/checkpoints # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
model_name: metadrive_park_3
model_epoch: latest

seed: 75
n_evals: 2
goal_source: 'random_state'
goal_H: 5
n_plot_samples: 5

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 2 
  mode: last

# planner:
#   _target_: planning.mpc_park.MPCPlanner
#   max_iter: null 
#   n_taken_actions: 1
#   sub_planner:
#     target: planning.cem.CEMPlanner
#     horizon: 8
#     topk: 30
#     num_samples: 400
#     var_scale: 1
#     opt_steps: 20
#     eval_every: 1
#   name: mpc_cem

planner:
  _target_: planning.mpc_park_full.MPCPlanner
  max_iter: null 
  n_taken_actions: 5
  sub_planner:
    target: planning.mppi.MPPIPlanner
    horizon: 5
    num_samples: 400
    opt_steps: 5
    eval_every: 1
    # 👇 新版参数 👇
    temperature: 0.1         
    noise_sigma: 0.5         
    num_control_points: 4  # 👈 核心降维参数！无论 horizon 是 10 还是 20，它永远只在 4 个点的空间里搜索
  name: mpc_mppi             # 👈 改个帅气的名字